#ifndef MIMETYPE_H
#define MIMETYPE_H

enum MIMEType
{
    FILE_TYPE_UNKNOW = 0,
    FILE_TYPE_DIRECTORY,
    FILE_TYPE_SYMBOLIC_LINK,

    FILE_TYPE_AUDIO,
    FILE_TYPE_IMAGE,

    FILE_TYPE_TEXT_CSS,
    FILE_TYPE_TEXT_CSV,
    FILE_TYPE_TEXT_PHP,
    FILE_TYPE_TEXT_XML,
    FILE_TYPE_TEXT_HTML,
    FILE_TYPE_TEXT_PLAIN,
};

#endif // MIMETYPE_H
